fixtures:
  symlinks:
    shared_infra: "#{source_dir}"
    stdlib: "#{source_dir}/spec/fixtures/r10k/stdlib"
    mysql: "#{source_dir}/spec/fixtures/r10k/mysql"
    docker: "#{source_dir}/spec/fixtures/r10k/docker"
    firewall: "#{source_dir}/spec/fixtures/r10k/firewall"
    archive: "#{source_dir}/spec/fixtures/r10k/archive"
    apt: "#{source_dir}/spec/fixtures/r10k/apt"
