fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    mysql: "puppetlabs/mysql"
    docker:
      repo: "puppetlabs/docker"
      ref: "10.1.0"
    firewall: "puppetlabs/firewall"
    archive: "puppet/archive"
    apt: "puppetlabs/apt"
  symlinks:
    shared_infra: "#{source_dir}"
